on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  verify-job:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/devcontainers/universal:2-focal
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Init and Verify Languages
        run: bash resources/topLevelVerify.sh

